### ISSUE TITLE
compat issue

### ISSUE THREAD

**Issue by jlchan** [pazner/TriplotRecipes.jl#1]
```julia
(test) pkg> add https://github.com/pazner/TriplotRecipes.jl/
     Cloning git-repo `https://github.com/pazner/TriplotRecipes.jl`
    Updating git-repo `https://github.com/pazner/TriplotRecipes.jl`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TriplotBase [981d1d27]:
 TriplotBase [981d1d27] log:
 ├─TriplotBase [981d1d27] has no known versions!
 └─restricted to versions * by TriplotRecipes [808ab39a] — no versions left
   └─TriplotRecipes [808ab39a] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─TriplotRecipes [808ab39a] is fixed to version 0.1.0
```
I can get around this by adding TriplotBase locally, but committing the Manifest.toml file or registering would fix this (though I think committing Manifest.toml is only guaranteed to work for the version of Julia used to generate the Manifest).

**Comment by pazner** [comment]
Registering TriplotBase will fix this. I don't think adding the Manifest will fix it though.

**Comment by jlchan** [comment]
Would you mind registering TriplotBase.jl and TriplotRecipes.jl after all? We're using these in https://github.com/trixi-framework/Trixi.jl/pull/755 now and we need all dependencies to be registered.

**Comment by pazner** [comment]
PR created to register TriplotBase.jl: https://github.com/JuliaRegistries/General/pull/41920

Once that is merged, I can register this package.

(It would be nice if JuliaLang/Pkg.jl#1628 was merged…)

**Comment by jlchan** [comment]
Thanks! Is TriplotRecipes being registered too?

And agreed on https://github.com/JuliaLang/Pkg.jl/pull/1628...

**Comment by pazner** [comment]
> Is TriplotRecipes being registered too?

Yes, but I cannot register TriplotRecipes until its dependency TriplotBase is registered, which will take 3 days.

**Comment by jlchan** [comment]
Gotcha, thanks. I had this issue a while back too...

**Comment by pazner** [comment]
TriplotBase is registered. PR opened for TriplotRecipes, it should be registered automatically in 3 days. JuliaRegistries/General#42138

**Comment by pazner** [comment]
It's registered! Let me know if there are any issues.

**Comment by jlchan** [comment]
Thanks for registering both packages! Looking forward to incorporating them in Trixi.
